global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter_1:9121'] # redis_exporter_1是你的redis-exporter container name